pr: false
worktree: false
validationPrompt: docs/dod.md
autoRelease: true
env:
  GOPATH: /home/node/go
  GOCACHE: /home/node/.cache/go-build
  GOLANGCI_LINT_CACHE: /home/node/.cache/golangci-lint
extraMounts:
  - src: ../docs
    dst: /docs
  - src: ${GOPATH}/pkg
    dst: /home/node/go/pkg
  - src: ${HOME}/Library/Caches/go-build
    dst: /home/node/.cache/go-build
  - src: ${HOME}/Library/Caches/golangci-lint
    dst: /home/node/.cache/golangci-lint
